### ISSUE TITLE
Source of the Anthropic OpenAPI spec

### ISSUE THREAD

**Issue by corbt** [tryAGI/Anthropic#1]
### Describe the bug

Hey there! Apologies for creating an issue, just not sure where else to ask this: where did you find the Anthropic [OpenAPI spec](https://github.com/tryAGI/Anthropic/blob/main/docs/openapi.yaml)? I'm working on another project ([OpenPipe](https://openpipe.ai/)) and it would be really helpful to use that file for codegen.

### Steps to reproduce the bug

1. Visit https://docs.anthropic.com/claude
2. Can't find OpenAPI spec 😂

**Comment by HavenDV** [comment]
Hi.
They still don't expose the official OpenAPI: https://github.com/anthropics/anthropic-sdk-python/issues/71
This spec was written by me by hand based on the official docs.

**Comment by corbt** [comment]
Got it, thanks for responding!
