### ISSUE TITLE
CreateMessageRequest > Tools > Tool > InputSchema - allow other implementations of JsonSchema

### ISSUE THREAD

**Issue by WimSuenens** [tryAGI/Anthropic#56]
The SDK provides it's own implementation of a JsonSchema through `Anthropic.OpenApiSchema`/`Anthropic.ToolInputSchema`.

I'm using [`NJsonSchema`](https://github.com/RicoSuter/NJsonSchema) to generate a `JsonSchema` from a C# `class`.

```cs
public JsonSchema TypeToJsonSchema<T>()
{
    JsonSchemaGeneratorSettings settings = new SystemTextJsonSchemaGeneratorSettings()
    {
        SchemaType = SchemaType.OpenApi3,
        SerializerOptions = new JsonSerializerOptions()
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower
        },
    };
    return JsonSchema.FromType<T>(settings);
}
```

Afterwards, I use `AutoMapper` to map from a `JsonSchema` to a `ToolInputSchema`. However, during the mapping I'm losing my `definitions` and other relevant data from the original `JsonSchema` like `$refs`, ...

```cs
var schema = _jsonSchemaService.TypeToJsonSchema<MyClass>();
var tool = _mapper.Map<ToolInputSchema>(schema);
```

It would be nice, if users could provide their own type of JsonSchema, depending on the library used `NJsonSchema`, `Newtonsoft`, `json-everything`, ...

Could this be solved by a `generic` class?

```cs
public class Tool<T>
{
    public string Name { get; set; }
    public string? Description { get; set; }
    public T InputSchema { get; set; }
}
```

**Comment by HavenDV** [comment]
Yes, I am thinking about this and unifying this functionality among OpenAI/Anthropic/Ollama/LangChain.Providers libraries.
The main problem here is trimming/NativeAOT support. When serializing/deserializing, these custom types must be defined for System.Text.Json TypeResolver, and we need to think about how to do this for external types in a convenient way

**Comment by HavenDV** [comment]
@WimSuenens I also recommend you take a look at https://learn.microsoft.com/en-us/dotnet/api/system.text.json.schema.jsonschemaexporter?view=net-8.0
